一些Array之间的操作

In [2]:
import numpy as np
a = np.diag([2,3,4,5,6])
a = np.vstack((np.zeros(5),a))
np.disp(a)

[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 6.]]


实现一个矩阵相乘

In [6]:
import numpy as np
a = np.array([1,2]).transpose()
b = np.array([3,4])
# 按元素相乘
print((a.T)*b)
# 矩阵相乘
print(np.dot(a,b))

[3 8]
11
